# COMP3330/6380 Python Introduction

## Numpy

Numpy is a fundamental numeric computing package for Python. Numpy includes functionality to create N-dimensional arrays, tools for integrating C/C++ code, and provides many mathematical functions.

In [1]:
import numpy as np

a = np.array([3, 2, 1]) #create an array from a list

print(a, type(a))
print(a.shape)
print(a[0], a[-1], a[1:], a[:2]) #we can slice numpy arrays

(array([3, 2, 1]), <type 'numpy.ndarray'>)
(3,)
(3, 1, array([2, 1]), array([3, 2]))


In [2]:
b = np.array([[3, 2, 1],[6, 5, 4]]) #create 2d array

print(b, type(b))
print(b.shape)
print(b[0, 1], b[1, -1], b[1:], b[:2])

(array([[3, 2, 1],
       [6, 5, 4]]), <type 'numpy.ndarray'>)
(2, 3)
(2, 4, array([[6, 5, 4]]), array([[3, 2, 1],
       [6, 5, 4]]))


In [3]:
c = np.zeros((3,2)) #create an array of zeros of given size
print(c)

d = np.ones((2,3)) #create an array of ones of given size
print(d)

e = np.random.random((4,2)) #create an array of random numbers of given size
print(e)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.20418615  0.00904342]
 [ 0.24937071  0.46074931]
 [ 0.80199387  0.99532607]
 [ 0.17083691  0.20283824]]


In [4]:
#arange creates an array containing evenly spaced numbers within a given interval
#numpy.arange(start, stop, step)
f = np.arange(4) 
print(f)

g = np.arange(1, 2, 0.1)
print(g)

[0 1 2 3]
[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9]


In [5]:
h = np.arange(0, 10)
i = np.arange(10, 20)

print(np.add(h, i))

print(np.subtract(h, i))

print(np.multiply(h, i))

print(np.divide(h, i))

[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[  0  11  24  39  56  75  96 119 144 171]
[0 0 0 0 0 0 0 0 0 0]


In [6]:
j = np.arange(1, 12)

j = np.sqrt(j)

print(np.power(j, 2))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]


In [7]:
k = np.array([3, 4])
l = np.array([5, 6])

print(np.dot(k, l)) #computes dot product

39


In [8]:
#numpy includes mathematical constants
print(np.pi)

print(np.e)

3.14159265359
2.71828182846
